set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_0__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.91 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_1__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.83 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_2__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.75 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_3__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.67 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_4__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.59 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_5__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.52 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_6__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.44 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_7__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.36 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_8__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.28 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_9__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.20 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_10__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.13 -0.15} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_11__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.05 -0.15} -offset_type scalable

set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_0__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.91 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_1__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.83 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_2__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.75 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_3__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.67 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_4__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.59 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_5__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.52 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_6__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.44 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_7__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.36 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_8__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.28 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_9__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.20 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_10__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.13 -0.35} -offset_type scalable
set_macro_relative_location -target_object [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_11__RAMW}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.05 -0.35} -offset_type scalable

set_macro_relative_location -target_object [get_cell {PIXELS_RAM_genblk1_0__RAME}] -target_orientation R180 -target_corner tr -anchor_corner tr -offset {-0.5 -0.6} -offset_type scalable
create_macro_relative_location_placement

set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_0__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_1__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_2__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_3__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_4__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_5__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_6__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_7__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_8__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_9__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_10__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_11__RAMW}] -name physical_status -value fixed

set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_0__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_1__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_2__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_3__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_4__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_5__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_6__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_7__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_8__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_9__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_10__RAMW}] -name physical_status -value fixed
set_attribute -objects [get_cell {WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_11__RAMW}] -name physical_status -value fixed

set_attribute -objects [get_cell {PIXELS_RAM_genblk1_0__RAME}] -name physical_status -value fixed

create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_0__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_0__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_0__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_1__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_1__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_1__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_2__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_2__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_2__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_3__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_3__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_3__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_4__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_4__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_4__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_5__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_5__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_5__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_6__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_6__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_6__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_7__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_7__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_7__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_8__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_8__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_8__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_9__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_9__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_8__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_10__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_10__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_10__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_11__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_11__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_0__BRAM_BRAM_genblk1_11__RAMW] ref_block];

create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_0__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_0__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_0__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_1__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_1__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_1__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_2__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_2__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_2__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_3__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_3__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_3__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_4__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_4__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_4__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_5__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_5__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_5__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_6__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_6__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_6__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_7__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_7__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_7__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_8__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_8__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_8__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_9__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_9__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_8__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_10__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_10__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_10__RAMW] ref_block];
create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_11__RAMW] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_11__RAMW] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells WEIGHTS_ROTATOR_genblk1_1__BRAM_BRAM_genblk1_11__RAMW] ref_block];

create_keepout_margin -type hard -outer {5 5 5 5} [get_attribute [get_cells PIXELS_RAM_genblk1_0__RAME] ref_block];create_keepout_margin -type hard_macro -outer {5 5 5 5} [get_attribute [get_cells PIXELS_RAM_genblk1_0__RAME] ref_block];create_keepout_margin -type soft -outer {8 8 8 8} [get_attribute [get_cells PIXELS_RAM_genblk1_0__RAME] ref_block];

