# all rules: https://github.com/dalance/svlint/blob/master/MANUAL.md
# example: https://github.com/lowRISC/ibex/blob/master/.svlint.toml

[option]
exclude_paths = ["asic/*", "fpga/*"]

[rules]
non_ansi_module = true
keyword_forbidden_wire_reg = true
input_with_var = false
output_with_var = false
parameter_default_value = true