#ifndef CGRA4ML_REGS_H
#define CGRA4ML_REGS_H

// CGRA4ML AXI-Lite register map.
//
// These offsets follow deepsocflow/c/runtime.h.
// The runtime treats p_config as int32_t*, so A_* values are word offsets.
// This file exposes byte offsets for Linux ioread32/iowrite32.

#define CGRA4ML_REG_WORD_BYTES      4U
#define CGRA4ML_WORD_OFFSET(x)      ((x) * CGRA4ML_REG_WORD_BYTES)

// Runtime register word offsets
#define CGRA4ML_A_START             0x0
#define CGRA4ML_A_DONE_READ         0x1
#define CGRA4ML_A_DONE_WRITE        0x3
#define CGRA4ML_A_OCM_BASE          0x5
#define CGRA4ML_A_WEIGHTS_BASE      0x7
#define CGRA4ML_A_BUNDLE_DONE       0x8
#define CGRA4ML_A_N_BUNDLES_1       0x9
#define CGRA4ML_A_W_DONE            0xA
#define CGRA4ML_A_X_DONE            0xB
#define CGRA4ML_A_O_DONE            0xC

#define CGRA4ML_A_PARAM_BASE        0x10

// Byte offsets
#define CGRA4ML_REG_START           CGRA4ML_WORD_OFFSET(CGRA4ML_A_START)
#define CGRA4ML_REG_DONE_READ0      CGRA4ML_WORD_OFFSET(CGRA4ML_A_DONE_READ + 0)
#define CGRA4ML_REG_DONE_READ1      CGRA4ML_WORD_OFFSET(CGRA4ML_A_DONE_READ + 1)
#define CGRA4ML_REG_DONE_WRITE0     CGRA4ML_WORD_OFFSET(CGRA4ML_A_DONE_WRITE + 0)
#define CGRA4ML_REG_DONE_WRITE1     CGRA4ML_WORD_OFFSET(CGRA4ML_A_DONE_WRITE + 1)
#define CGRA4ML_REG_OCM_BASE0       CGRA4ML_WORD_OFFSET(CGRA4ML_A_OCM_BASE + 0)
#define CGRA4ML_REG_OCM_BASE1       CGRA4ML_WORD_OFFSET(CGRA4ML_A_OCM_BASE + 1)
#define CGRA4ML_REG_WEIGHTS_BASE    CGRA4ML_WORD_OFFSET(CGRA4ML_A_WEIGHTS_BASE)
#define CGRA4ML_REG_BUNDLE_DONE     CGRA4ML_WORD_OFFSET(CGRA4ML_A_BUNDLE_DONE)
#define CGRA4ML_REG_N_BUNDLES       CGRA4ML_WORD_OFFSET(CGRA4ML_A_N_BUNDLES_1)
#define CGRA4ML_REG_W_DONE          CGRA4ML_WORD_OFFSET(CGRA4ML_A_W_DONE)
#define CGRA4ML_REG_X_DONE          CGRA4ML_WORD_OFFSET(CGRA4ML_A_X_DONE)
#define CGRA4ML_REG_O_DONE          CGRA4ML_WORD_OFFSET(CGRA4ML_A_O_DONE)
#define CGRA4ML_REG_PARAM_BASE      CGRA4ML_WORD_OFFSET(CGRA4ML_A_PARAM_BASE)

#define CGRA4ML_DEFAULT_REG_SIZE    0x10000

#endif
